name: 'Buildout'
description: 'Buildout using a given python version'
inputs:
  py-version:
    description: 'python version'
    required: true
    default: '3.8'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.py-version }}
    - name: Install dependencies
      run: |
        pip install -U pip setuptools coveralls coverage
        pip install -r requirements.txt -c constraints_plone52.txt
        pre-commit install
      shell: bash
    - name: buildout
      run: |
        buildout -c test_plone52.cfg buildout:download-cache=./buildout-cache/downloads buildout:eggs-directory=./buildout-cache/eggs
      shell: bash
