# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Branch Coverage

on:
  push:

jobs:
  coverage:
    runs-on:
      group: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        plone-version: ["6.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }} }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
      - name: Buildout action
        uses: IMIO/plonemeeting.portal.core/actions/buildout/@master
        with:
          py-version: ${{ matrix.python-version }}
          plone-version: ${{ matrix.plone-version }}
      - name: Coverage action
        uses: IMIO/plonemeeting.portal.core/actions/coverage/@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
