name: Branch Coverage

on:
  push:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: gha-runners-delib-py3
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        plone-version: ["6.1"]
    steps:
      - name: Run check
        uses: IMIO/gha/plone-package-test-notify@v4.1.1
        env:
          cache-name: cache-eggs
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-Plone6.1-${{ matrix.python-version }}
          TEST_COMMAND: coverage run bin/test
          INSTALL_DEPENDENCIES_COMMANDS: 'pip install -r requirements-tests.txt'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          BUILDOUT_CONFIG_FILE: 'test-${{ matrix.plone-version }}.cfg'
      - name: Report
        run: |
          coverage report
          coverage xml
        shell: bash
      - name: Publish to Coveralls
        run: |
          coveralls --service=github
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
