name: Code Analysis

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on:
      group: self-hosted
    steps:
      - name: Run checks
        uses: IMIO/gha/code-analysis-notify@main
        with:
          CHECK: 'black'
          BASE_DIR: 'src'
          PATH: |
            plonemeeting
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
