name: Code Analysis

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on:
      group: self-hosted
    steps:
      - name: Run checks (black)
        uses: IMIO/gha/code-analysis-notify@main
        with:
          CHECK: 'black'
          BASE_DIR: '.'
          PATH: |
            src
            setup.py
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
      - name: Run checks (flake8)
        uses: IMIO/gha/code-analysis-notify@main
        with:
          CHECK: 'flake8'
          BASE_DIR: '.'
          PATH: |
            src
            setup.py
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
      - name: Run checks (isort)
        uses: IMIO/gha/code-analysis-notify@main
        with:
          CHECK: 'isort'
          BASE_DIR: '.'
          PATH: |
            src
            setup.py
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
