name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: gha-runners-delib-py3
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        plone-version: ["6.0"]
        experimental: [false]
    steps:
      - name: Run tests
        uses: IMIO/gha/plone-package-test-notify@v3
        env:
          cache-name: cache-eggs
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
          TEST_COMMAND: bin/test
          REQUIREMENTS_FILE: 'requirements-tests.txt'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          BUILDOUT_CONFIG_FILE: 'test-${{ matrix.plone-version }}.cfg'
  coverage:
    runs-on: gha-runners-delib-py3
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        plone-version: ["6.0"]
        experimental: [false]
    steps:
      - name: Run coverage
        uses: IMIO/gha/plone-package-test-notify@main
        env:
          cache-name: cache-eggs
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
          TEST_COMMAND: coverage run bin/test
          INSTALL_DEPENDENCIES_COMMANDS: 'pip install -r requirements-tests.txt'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          BUILDOUT_CONFIG_FILE: 'test-${{ matrix.plone-version }}.cfg'
      - name: Report
        run: |
          coverage report
          coverage xml
        shell: bash
      - name: Publish to Coveralls
        run: |
          coveralls --service=github
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cobertura
        uses: 5monkeys/cobertura-action@v9
        with:
          path: coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 90
