name: Test package

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: gha-runner-delib-py3
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        plone-version: ["6.0"]
        experimental: [false]
    steps:
      - name: Run tests
        uses: IMIO/gha/plone-package-test-notify@main
        env:
          cache-name: cache-eggs
        with:
          CACHE_KEY: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}
          TEST_COMMAND: bin/test
          REQUIREMENTS_FILE: 'requirements-tests.txt'
          MATTERMOST_WEBHOOK_URL: ${{ secrets.DELIB_MATTERMOST_WEBHOOK_URL }}
          BUILDOUT_CONFIG_FILE: 'test-${{ matrix.plone-version }}.cfg'