# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test package

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        plone-version: ["6.0"]
        experimental: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache eggs
        uses: actions/cache@v2
        env:
          cache-name: cache-eggs
        with:
          path: ./buildout-cache/eggs
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}-${{ matrix.plone-version }} }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.python-version }}-${{ matrix.plone-version }}
      - name: Buildout action
        uses: IMIO/plonemeeting.portal.core/actions/buildout@master
        with:
          py-version: ${{ matrix.python-version }}
          plone-version: ${{ matrix.plone-version }}
      - name: code analysis
        run: |
          pre-commit run --all-files
      - name: Test
        run: |
          bin/test
